# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/ZyboZ7.xdc

# Block Designs: bd/ZyboBreakoutScoreCalc/ZyboBreakoutScoreCalc.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZyboBreakoutScoreCalc || ORIG_REF_NAME==ZyboBreakoutScoreCalc} -quiet] -quiet

# IP: bd/ZyboBreakoutScoreCalc/ip/ZyboBreakoutScoreCalc_processing_system7_0_0/ZyboBreakoutScoreCalc_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZyboBreakoutScoreCalc_processing_system7_0_0 || ORIG_REF_NAME==ZyboBreakoutScoreCalc_processing_system7_0_0} -quiet] -quiet

# IP: bd/ZyboBreakoutScoreCalc/ip/ZyboBreakoutScoreCalc_ZyboBreakoutScore_0_1/ZyboBreakoutScoreCalc_ZyboBreakoutScore_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZyboBreakoutScoreCalc_ZyboBreakoutScore_0_1 || ORIG_REF_NAME==ZyboBreakoutScoreCalc_ZyboBreakoutScore_0_1} -quiet] -quiet

# IP: bd/ZyboBreakoutScoreCalc/ip/ZyboBreakoutScoreCalc_ps7_0_axi_periph_0/ZyboBreakoutScoreCalc_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZyboBreakoutScoreCalc_ps7_0_axi_periph_0 || ORIG_REF_NAME==ZyboBreakoutScoreCalc_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/ZyboBreakoutScoreCalc/ip/ZyboBreakoutScoreCalc_rst_ps7_0_50M_0/ZyboBreakoutScoreCalc_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZyboBreakoutScoreCalc_rst_ps7_0_50M_0 || ORIG_REF_NAME==ZyboBreakoutScoreCalc_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/ZyboBreakoutScoreCalc/ip/ZyboBreakoutScoreCalc_auto_pc_0/ZyboBreakoutScoreCalc_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZyboBreakoutScoreCalc_auto_pc_0 || ORIG_REF_NAME==ZyboBreakoutScoreCalc_auto_pc_0} -quiet] -quiet

# XDC: bd/ZyboBreakoutScoreCalc/ZyboBreakoutScoreCalc_ooc.xdc
